In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:

df = pd.read_excel('Gastos y costos 20-23.xlsx',skiprows=5,sheet_name="2020")
df

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,POLIZA,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,NaN,"Descripci√≥n: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,NaN,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,NaN,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,NaN,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,NaN,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,NaN,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,NaN,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,NaN,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,G VTA,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente,NaN,0.00
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,G VTA,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente,NaN,0.00
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,G VTA,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente,NaN,0.00
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,G FINA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,NaN,0.00
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,G VTA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente,NaN,0.00

In [53]:
valores_nulos2=df.isnull().sum()
valores_nulos2

FECHA             0
FOLIO           189
UUID              0
RFC               0
PROVEEDOR         0
TIPO GASTO        0
GASTO          2502
DESCRIPCION       0
TC              391
IMPORTE          34
IVA             268
RET ISR           0
RET IVA           0
TOTAL MX          0
TOTAL SAT         0
TIPO              1
STATUS            0
POLIZA         3321
Columna1          0
dtype: int64

In [54]:
valores_nulos2=df.isnull().sum().sum()
valores_nulos2

6706

In [55]:
df = df.drop(['POLIZA', 'GASTO'], axis=1)

SE ELIMINARON COLUMNAS COMO POLIZA Y GASTO POR QUE TENIAN MAS DE LA MITAD DE SUS DATOS COMO VALORES NULOS POR LO QUE LA INFORMACION RECABADA NO ES SUFICIENTE PARE SER SIGNIFICANTE EN COMPARACI√ìN A LOS OTROS DATOS

In [56]:

valores_nulos2=df.isnull().sum().sum()
valores_nulos2

883

In [57]:
valores_nulos2=df.isnull().sum()
valores_nulos2

FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
DESCRIPCION      0
TC             391
IMPORTE         34
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
Columna1         0
dtype: int64

In [58]:
df

,FECHA,FOLIO,UUID,RFC,PROVEEDOR,TIPO GASTO,DESCRIPCION,TC,IMPORTE,IVA,RET ISR,RET IVA,TOTAL MX,TOTAL SAT,TIPO,STATUS,Columna1
0,2020-01-01,39408,BD20F436-72CC-4BE2-AD37-5999D71AA391,ARE080115PBA,ARSI RENTA SA DE CV,MAQUINARIA,"Descripci√≥n: REVOLVEDORA, Modelo: ULTRAMP9A, M...",1.0,0.00,2248.28,0.0,0.0,2248.28,16300.00,I,Vigente,14051.72
1,2020-01-01,0001010100750847116902,85AEAC2E-6395-44A0-9CB9-754D06893375,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,1.0,490.00,78.40,0.0,0.0,568.40,568.40,I,Vigente,0.00
2,2020-01-01,0001010100752163714102,BD0DFE85-D776-41CB-9C5C-4FA7923E687A,BNM840515VB1,"BANCO NACIONAL DE MEXICO, S.A.",COMISION BANCARIA,COMISION COBRADA,1.0,195.00,31.20,0.0,0.0,226.20,226.20,I,Vigente,0.00
3,2020-01-01,3663,EF4504D6-830D-415C-AF03-80CF54C5E28E,PSS120625C86,PROMOTORA DE SERVICIOS Y SOLUCIONES EMPRESARIA...,HONORARIOS CONTABLES,HONORARIOS CONTABLES\nDEL MES DE ENERO DEL 2020.,1.0,10694.25,1711.08,0.0,0.0,12405.33,12405.33,I,Vigente,0.00
4,2020-01-01,2849,EC2F4AA4-BA64-4E2E-A5B7-4EBBE042D6D3,ENA7006081P0,ELECTROTERMICA NACIONAL SA DE CV,COMPRAS,Pago,1.0,0.00,NaN,0.0,0.0,0.00,0.00,P,Vigente,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3337,2020-12-01,125834,80BCB1D8-673F-495B-9C2A-4AC9F9CB38E5,SQS110113MU0,SERVICIO QUINTANA SUR S.A DE C.V,COMBUSTIBLE,32011 MAGNA,1.0,129.79,20.21,0.0,0.0,150.00,150.00,I,Vigente,0.00
3338,2020-12-01,37652,D4C7C1FB-03A7-4046-A2BD-03EBE7DA861E,PSQ790724C90,"CIA. PERIODISTICA DEL SOL DE QUERETARO, S.A. D...",PUBLICIDAD,82101504-PUBLICIDAD EN PERIODICOSCALOR Y CONTROL,1.0,2284.80,365.57,0.0,0.0,2650.37,2650.37,I,Vigente,0.00
3339,2020-12-01,160,FFCEE7D4-1F38-4D44-BE02-EB042DAACEE7,SQX981027RY5,"SUPER Q, S. A. DE C. V.",ALIMENTOS,REF VICTORIA GROSELLA 3 LT PET NR,1.0,163.79,26.21,0.0,0.0,190.00,190.00,I,Vigente,0.00
3340,2020-12-01,634875,8DFF4F01-2F8B-4085-B116-05A314108B02,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,1.0,0.00,0.00,0.0,0.0,0.00,0.00,I,Vigente,0.00
3341,2020-12-01,1044477,F18225D6-4024-4F03-A15A-D18917386D59,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,COMBUSTIBLE,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,1.0,14889.29,0.00,0.0,0.0,14889.29,14889.29,I,Vigente,0.00

In [59]:


df["TC"].fillna(0,inplace = True)
print(df.isnull().sum())

FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
DESCRIPCION      0
TC               0
IMPORTE         34
IVA            268
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
Columna1         0
dtype: int64

TC se decidio asi por que todos los datos son 1 o 0 en su mayoria, hay muy pocos que se salen de este rango asi que se decidio asi por que si son nulos podrian ser simplemente definidos como 0

In [63]:
df['IVA'] = df['IVA'].fillna(df['IMPORTE'] * 0.16)
print(df.isnull().sum())

FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
DESCRIPCION      0
TC               0
IMPORTE         16
IVA             16
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
Columna1         0
dtype: int64

In [61]:
df['IMPORTE'] = df['IMPORTE'].fillna(df['IVA'] * 6.25)
print(df.isnull().sum())

FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
DESCRIPCION      0
TC               0
IMPORTE         16
IVA             16
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
Columna1         0
dtype: int64

In [64]:
df['IMPORTE'] = df['IMPORTE'].fillna(df['TOTAL MX'] * 0.84)
print(df.isnull().sum())

FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
DESCRIPCION      0
TC               0
IMPORTE          0
IVA             16
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
Columna1         0
dtype: int64

In [65]:
df['IVA'] = df['IVA'].fillna(df['TOTAL MX'] * 0.16)
print(df.isnull().sum())

FECHA            0
FOLIO          189
UUID             0
RFC              0
PROVEEDOR        0
TIPO GASTO       0
DESCRIPCION      0
TC               0
IMPORTE          0
IVA              0
RET ISR          0
RET IVA          0
TOTAL MX         0
TOTAL SAT        0
TIPO             1
STATUS           0
Columna1         0
dtype: int64

**Las variables de IMPORTE,IVA y TOTAL MXN se complementan y son dependientes la una de la otra asi que solo se utiliza el saber que el IVA actual mexicano es de 16% y se rellenan los datos**

In [66]:
df["FOLIO"].fillna("N999999999",inplace = True)
print(df.isnull().sum())

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           1
STATUS         0
Columna1       0
dtype: int64

In [67]:
df["TIPO"].fillna("NO SE SABE",inplace = True)
print(df.isnull().sum())

FECHA          0
FOLIO          0
UUID           0
RFC            0
PROVEEDOR      0
TIPO GASTO     0
DESCRIPCION    0
TC             0
IMPORTE        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
TIPO           0
STATUS         0
Columna1       0
dtype: int64

Aqui se decidio poner eso ya que es un dato que la misma tienda define y se define como independiente por lo cual no tiene patr√≥n o variable que lo defina o dependa de su resultado a simple vista

In [68]:
df2 = pd.read_excel('Gastos y costos 20-23.xlsx',skiprows=3,sheet_name="2023")
df2

,Fecha,Folio,UUID,RFC,Proveedor,TIPO GASTO,Descripci√≥n,MP,FP,TC,Importe,IVA,RET ISR,RET IVA,Otros,TOTAL MX,TOTAL SAT,Tipo,Status,Poliza
0,2023-01-01,31,49536321-60A4-523E-A32F-E8BDF5C2276E,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
1,2023-01-01,38,20FBB63B-D550-512F-9668-EEC6F983CEB7,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN
2,2023-01-01,341932,DB8C4388-D4E0-4F0C-A09C-77C773257F44,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006876 30/36 de 03/12/...,PPD,99.0,1.0,5551.38,888.22,0.0,0.0,NaN,6439.60,6439.60,I,Vigente,PE01-ENE23
3,2023-01-01,341933,A81A63F5-D5EC-4601-803E-375AF9CC5021,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000006877 30/36 de 03/12/...,PPD,99.0,1.0,5551.98,888.32,0.0,0.0,NaN,6440.30,6440.30,I,Vigente,PE02-ENE23
4,2023-01-01,342205,DCC10492-DE51-4C87-8430-5676FBF81931,BLE1512082R9,BEPENSA LEASING S.A. DE C.V.,ARRENDAMIENTO FINANCIERO,AA RENTA EXIGIBLE CL0000009486 5/48 de 03/12/2...,PPD,99.0,1.0,8454.37,1352.70,0.0,0.0,NaN,9807.07,9807.07,I,Vigente,PE03-ENE23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392,2023-02-01,882974,3E97C399-6747-4BCA-8436-ED4B0933DF33,BIN940223KE0,"BANCO INVEX, S.A., INSTITUCION DE BANCA MULTIP...",COMISION BANCARIA,COMISIONES E INTERESES,PUE,3.0,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,I,Vigente,NaN
393,2023-02-01,053560,B7132758-F800-4797-B1D6-CC61AFFEE444,BPU7901018D4,BEBIDAS PURIFICADAS,ALIMENTOS,Epura 20 Lts Policarbonato,PUE,1.0,1.0,220.00,0.00,0.0,0.0,NaN,220.00,220.00,I,Vigente,NaN
394,2023-02-01,1092957089,D1E2DC1E-9FFB-46C6-82E4-B350B83CB6F7,BMN930209927,BANCO MERCANTIL DEL NORTE SA INSTITUCION DE BA...,COMISION BANCARIA,SERVICIOS BANCARIOS,PUE,3.0,1.0,18071.52,682.40,0.0,0.0,NaN,18753.92,18753.92,I,Vigente,NaN
395,2023-02-01,1453820,6249FE27-6FA6-4EFB-910E-3CD67A0E29A1,EFE8908015L3,EFECTIVALE S. de R.L. de C.V.,GASOLINA,CONSUMOS DE COMBUSTIBLE DE MONEDEROS ELECTRONICOS,PUE,5.0,1.0,14472.32,0.00,0.0,0.0,NaN,14472.32,14472.32,I,Vigente,NaN
396,2023-02-01,18,439A9230-277E-5563-818C-7630B0E8D706,AAE6411055P8,AESA ARTICULOS ELECTRICOS,COMPRAS,Pago,NaN,NaN,1.0,0.00,0.00,0.0,0.0,NaN,0.00,0.00,P,Vigente,NaN

In [70]:
valores_nulos2=df2.isnull().sum()
valores_nulos2

Fecha            0
Folio           13
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripci√≥n      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [73]:
df2["Folio"].fillna("N9999999999",inplace = True)
print(df2.isnull().sum())

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripci√≥n      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza         115
dtype: int64

In [76]:
df2["Poliza"].fillna("NOTEXIST",inplace = True)
print(df2.isnull().sum())

Fecha            0
Folio            0
UUID             0
RFC              0
Proveedor        0
TIPO GASTO       8
Descripci√≥n      0
MP              71
FP              71
TC               0
Importe          0
IVA              0
RET ISR          0
RET IVA          0
Otros          397
TOTAL MX         0
TOTAL SAT        0
Tipo             0
Status           0
Poliza           0
dtype: int64

In [77]:
df2 = df2.drop(['Otros'], axis=1)

In [79]:
df2["FP"].fillna("NOT",inplace = True)
print(df2.isnull().sum())

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     8
Descripci√≥n    0
MP             0
FP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [78]:
df2["MP"].fillna(999999,inplace = True)
print(df2.isnull().sum())

Fecha           0
Folio           0
UUID            0
RFC             0
Proveedor       0
TIPO GASTO      8
Descripci√≥n     0
MP              0
FP             71
TC              0
Importe         0
IVA             0
RET ISR         0
RET IVA         0
TOTAL MX        0
TOTAL SAT       0
Tipo            0
Status          0
Poliza          0
dtype: int64

In [80]:
df2["TIPO GASTO"].fillna("NO DEFINIDO",inplace = True)
print(df2.isnull().sum())

Fecha          0
Folio          0
UUID           0
RFC            0
Proveedor      0
TIPO GASTO     0
Descripci√≥n    0
MP             0
FP             0
TC             0
Importe        0
IVA            0
RET ISR        0
RET IVA        0
TOTAL MX       0
TOTAL SAT      0
Tipo           0
Status         0
Poliza         0
dtype: int64

In [81]:
df.to_csv("A√±o2020.csv")
df2.to_csv("A√±o2023.csv")